pipeline{
    agent {
        docker {
            image 'node:22'
            args '-u root:root'
        }
    }

    stages{
        stage('Verificar la versión de node instalada') {
            steps {
                sh 'node --version'
            }
        }

        stage("Instalar Playwright") {
            steps {
                script {
                    try {
                        sh '''
                        npm i -D @playwright/test
                        npx playwright install
                        npx playwright install-deps
                        '''
                    } catch (Exception e) {
                        error "Error instalando Playwright: ${e.getMessage()}"
                    }
                }
            }
        }

        stage ("Enlistar todos los casos de prueba") {
            steps {
                sh '''
                npx playwright test --list
                '''
            }
        }
    }
}