name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-24-04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Instalar dependencias
        run: npm install

      - name: Crear una carpeta para los reportes
        run: mkdir -p reportes

      - name: Correr los Tests
        run: npx mocha --reporter mochawesome --reporter-options reportDir=reportes, reportFilename=reporteAPITest-NodeJS --exit

      - name: Subir el reporte de MochaJS
        uses: actions/upload-artifact@v4
        with:
          name: Reporte de MochaJS
          path: reportes
