name: Playwright CI Test Pipeline
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Validar código
        uses: actions/checkout@v4

      - name: Instalar NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Instalar dependencias del modulo1
        working-directory: ./modulo1
        run: npm install

      - name: Instalar dependencias del modulo2
        working-directory: ./modulo2
        run: npm install

      - name: Instalar dependencias del modulo3
        working-directory: ./modulo3
        run: npm install

      - name: Instalar navegadores para Playwright (modulo1)
        working-directory: ./modulo1
        run: npx playwright install

      - name: Instalar navegadores para Playwright (modulo2)
        working-directory: ./modulo2
        run: npx playwright install

      - name: Instalar navegadores para Playwright (modulo3)
        working-directory: ./modulo3
        run: npx playwright install

      - name: Instalar Http-server via npm
        run: npm install -g http-server

      - name: Iniciar servidor HTTP en segundo plano
        run: |
          nohup http-server -p 5050 &

      - name: Esperar por el server para Iniciar tests de integración
        run: |
          while ! curl -s http://127.0.0.1:5050; do
            echo "Esperando al servidor"
            sleep 1
          done

      - name: Ejecutar tests de Playwright - Modulo1
        working-directory: ./modulo1
        run: npx playwright test
        continue-on-error: true

      - name: Ejecutar tests de Playwright - Modulo2
        working-directory: ./modulo2
        run: npx playwright test
        continue-on-error: true

      - name: Ejecutar tests de Playwright - Modulo3
        working-directory: ./modulo3
        run: npx playwright test
        continue-on-error: true

      - name: Ejecutar test específico - Module1 (browserAutomation)
        working-directory: ./modulo1
        run: npx playwright test tests/module1.spec.js
        continue-on-error: true

      - name: Ejecutar test específico - Module2 (mockAPI)
        working-directory: ./modulo2
        run: npx playwright test tests/module2-mockAPI.spec.js
        continue-on-error: true

      - name: Ejecutar test específico - Module3 (dataDriven)
        working-directory: ./modulo3
        run: npx playwright test tests/module3-dataDriven.spec.js
        continue-on-error: true
